IDEUS_DJANGO/IDEUS_DJANGO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('ideus.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IDEUS_DJANGO/ideus/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.index, name='index'),
    
    path('list/<modeltype>/<list_subject>/<sorting>/', views.model_list, name='model_list'),
    
    
    path('question/<int:pk>/', views.question_detail, name='question_detail'),
    
    path('new/question/', views.question_new, name='question_new'),
    path('new/answer/<int:pk>/', views.answer_new, name='answer_new'),
    path('new/result/<int:pk>/', views.result_new, name='result_new'),
    
    path('like/question/<int:pk>/', views.question_like, name='question_like'),
    path('like/answer/<int:pk>/', views.answer_like, name='answer_like'),
    path('like/result/<int:pk>/', views.result_like, name='result_like'),
    
    path('user/<int:user_id>/', views.user_detail, name='user_detail'),
]

IDEUS_DJANGO/ideus/models.py
from django.db import models
from IDEUS_DJANGO.constants import SUBJECT_CHOICES

#질문 모델
class Question(models.Model):
    username = models.CharField(max_length = 24)
    userid = models.IntegerField(null=True)
    
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    like = models.IntegerField(default=0)
    subject = models.IntegerField(default=0, choices=SUBJECT_CHOICES)
    answers = models.IntegerField(default=0)
def __str__(self):
    return self.title

#댓글 모델
class Answer(models.Model):
    username = models.CharField(max_length = 24)
    userid = models.IntegerField(null=True)
    
    question = models.ForeignKey('Question', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    like = models.IntegerField(default=0)
def __str__(self):
    return self.title

#결과물 공유
class Result(models.Model):
    username = models.CharField(max_length = 24)
    userid = models.IntegerField(null=True)
    
    question = models.ForeignKey('Question', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.URLField()
    
    like = models.IntegerField(default=0)
def __str__(self):
    return self.title

IDEUS_DJANGO/ideus/forms.py
from django import forms
from .models import Answer, Question, Result

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('title', 'content', 'photo')
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'content', 'subject', 'photo')
                  
class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ('title', 'link', 'content',)

IDEUS_DJANGO/ideus/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q

from IDEUS_DJANGO.constants import SUBJECT_CHOICES, SUBJECT_DICT
from accounts.models import User
from .models import Question, Answer, Result
from .forms import AnswerForm, QuestionForm, ResultForm
#index page
def index(request):
    waiting_question = Question.objects.filter(answers = 0).order_by('created_at')
    answer_question = Question.objects.filter(~Q(answers = 0)).order_by('created_at')
    return render(request, 'index.html', {
        'waiting_question': waiting_question,
        'answer_question': answer_question
    })

def user_detail(request, user_id):
    detail_user = get_object_or_404(User, id=user_id)
    user_answer = Answer.objects.filter(userid = detail_user.id).order_by('created_at')
    user_result = Result.objects.filter(userid = detail_user.id).order_by('created_at')
    
    like_subject = list()
    for i in detail_user.subject_like:
        like_subject.append(ord(i))
    favorite_subject = SUBJECT_DICT[like_subject.index(max(like_subject))]
        
    return render(request, 'user_detail.html', {
        'detail_user':detail_user,
        'user_answer':user_answer,
        'user_result':user_result,
        'favorite_subject': favorite_subject,
    })

def model_list(request, modeltype, list_subject, sorting):
    user = request.user
    
    if sorting == 'mylikes':    #내가 좋아한질문은 유저에서 불러와야하므로 예외
        if modeltype == 'question':
            result_list = user.like_question.order_by('-created_at')
            title = '질문'
        elif modeltype == 'answer':
            result_list = user.like_answer.order_by('-created_at')
            title = '답변'
        elif modeltype == 'result':
            result_list = user.like_result.order_by('-created_at')
            title = '결과물'
    elif modeltype == 'question':    #질문일경우
        result_list = Question.objects.all()
        title = '질문'
        #질문만 쓸수있는 정렬기준
        if sorting == 'manyanswer':
            result_list = result_list.order_by('-answers', '-created_at')
            title = '모든 질문'
        elif sorting == 'existanswer':
            result_list = result_list.filter(~Q(answers = 0)).order_by('-created_at')
            title = '아이디어를 받은 질문'
        elif sorting == 'noanswer':
            result_list = result_list.filter(answers = 0).order_by('-created_at')
            title = '아이디어를 기다리는 질문'
    elif modeltype == 'answer':        #답변일경우
            result_list = Answer.objects.all()
            title = '답변'
    elif modeltype == 'result':        #결과물일경우
            result_list = Result.objects.all()
            title = '결과물'
        
    #주제 선택
    if list_subject != 'all':    #all이면 필요없음
        list_subject = int(list_subject)    #정수형으로 변환
        if modeltype == 'question':
            result_list = result_list.filter(subject=list_subject)
            
    #정렬방식 선택
    if sorting == 'mylikes':    #mylikes는 이미 정렬했으므로 할필요없음
        title = '내가 좋아한 ' + title
    elif sorting == 'my':
        result_list = result_list.filter(userid=user.id)
        title = '내가 쓴 ' + title
    elif sorting == 'newest':   #모두해당하지 않을경우 기본(최신순)정렬
        result_list = result_list.order_by('-created_at')
        title = '모든 ' + title
    elif sorting == 'manylike':
        result_list = result_list.order_by('-like', '-created_at')
        title = '모든 ' + title
    elif modeltype == 'answer' or modeltype == 'result':
        return redirect('model_list', modeltype, list_subject, 'newest')
    
    #결과물 적용
    paginator = Paginator(result_list, 10)
    page = request.GET.get('page')
    pageposts = paginator.get_page(page)
    
    return render(request, modeltype + '_list.html', {
        'result_list': result_list,
        'pageposts': pageposts,
        'title': title,
        'subject': list_subject,
        'subject_dict': SUBJECT_DICT.items(),
        'sorting': sorting,
    })

def question_detail(request, pk):
    question = Question.objects.get(pk=pk)
    
    return render(request, 'question_detail.html', {
        'question': question,
    })

def result_new(request, pk):
    if not request.user.is_active:
        return redirect('question_detail', pk)
    
    if request.method == 'POST':
        form = ResultForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username=request.user)
            result = form.save()
            
            result.question = Question.objects.get(pk=pk)
            result.username = user.username
            result.userid = user.id
            user.my_result += 1
            if 'youtu' in result.link:
                result.link = 'https://www.youtube.com/embed/' + result.link[-11:]
            if 'vimeo' in result.link:
                result.link = 'https://player.vimeo.com/video/' + result.link[-9:] + '?title=0&byline=0&portrait=0'
            
            user.save()
            result.save()
            return redirect('question_detail', pk)
        else:
            messages.info(request, '필수값을 모두 입력해주세요')
            
    else:
        form = ResultForm()
    return render(request, 'result_form.html', {
        'form' : form,
    })

def answer_new(request, pk):
    if not request.user.is_active:
        return redirect('question_detail', pk)
    
    if request.method == 'POST':
        form = AnswerForm(request.POST, request.FILES)
        if form.is_valid():
            user = User.objects.get(username=request.user)
            question = Question.objects.get(pk=pk)
            answer = form.save()
            
            answer.question = Question.objects.get(pk=pk)
            answer.username = user.username
            answer.userid = user.id
            question.answers += 1
            user.subject_like = user.subject_like[:question.subject] + chr(ord(user.subject_like[question.subject])+2) + user.subject_like[question.subject+1:]
            
            user.save()
            question.save()
            answer.save()
            return redirect('question_detail', pk)
        else:
            messages.info(request, '필수값을 모두 입력해주세요')
    else:
        form = AnswerForm()
    
    return render(request, 'answer_form.html', {
        'form' : form,
    })

def question_new(request):
    if not request.user.is_active:
        return redirect('question_detail', pk)
    
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            user = User.objects.get(username=request.user)
            question = form.save()
            
            question.username = user.username
            question.userid = user.id
            user.my_question += 1
            user.subject_like = user.subject_like[:question.subject] + chr(ord(user.subject_like[question.subject])+3) + user.subject_like[question.subject+1:]
            
            user.save()
            question.save()
            return redirect('question_detail', question.id)
        else:
            messages.info(request, '필수값을 모두 입력해주세요')
    else:
        form = QuestionForm()
        return render(request, 'question_form.html', {
            'form' : form,
            'subject': SUBJECT_DICT.items(),
        })

def question_like(request, pk):
    if not request.user.is_active:
        return redirect('question_detail', pk)
    
    question = get_object_or_404(Question, id=pk)
    user = User.objects.get(username=request.user)
    if user.like_question.filter(id=pk).exists():
        user.like_question.remove(question)
        user.subject_like = user.subject_like[:question.subject] + chr(ord(user.subject_like[question.subject])-1) + user.subject_like[question.subject+1:]
        question.like -= 1
    else:
        user.like_question.add(question)
        user.subject_like = user.subject_like[:question.subject] + chr(ord(user.subject_like[question.subject])+1) + user.subject_like[question.subject+1:]
        question.like += 1
    
    user.save()
    question.save()
    return redirect('question_detail', pk)

def answer_like(request, pk):
    if not request.user.is_active:
        return redirect('question_detail', answer.question.id)
    
    answer = get_object_or_404(Answer, id=pk)
    user = User.objects.get(username=request.user)
    if user.like_answer.filter(id=pk).exists():
        user.like_answer.remove(answer)
        answer.like -= 1
    else:
        user.like_answer.add(answer)
        answer.like += 1
    answer.save()
    return redirect('question_detail', answer.question.id)

def result_like(request, pk):
    if not request.user.is_active:
        return redirect('question_detail', result.question.id)
    
    result = get_object_or_404(Result, id=pk)
    user = User.objects.get(username=request.user)
    if user.like_result.filter(id=pk).exists():
        user.like_result.remove(result)
        result.like -= 1
    else:
        user.like_result.add(result)
        result.like += 1
    result.save()
    return redirect('question_detail', result.question.id)

IDEUS_DJANGO/ideus/templates/answer_form.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>아이디어 주기|IDEUS</title>
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block content %}
{% if messages %}
    <hr color = "#3F3566">
    <form_title>
	{% for message in messages %}
        {{ message.message }}<br>
	{% endfor %}
    </form_title>
    <hr color = "#3F3566">
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <form_title><label for="{{form.title.id_for_label}}">제목</label></form_title>
    <input type="text" class="form-control" id="{{form.title.id_for_label}}" 
            placeholder="제목을 입력해주세요" name="{{form.title.name}}">
    
    <form_title><label for="{{form.content.id_for_label}}">내용</label></form_title>
    <textarea name="{{form.content.name}}" cols="40" rows="10" id="{{form.content.id_for_label}}" placeholder="내용을 입력해주세요"></textarea>
    
    <form_title style="color: #C6C3D1;"><label for="{{form.photo.id_for_label}}">이미지</label></form_title>
    <input type="file" name="{{ form.photo.name }}" accept="image/*" id="{{form.photo.id_for_label}}" style="background: #AC95D9;">
    
    <input type="submit" value="아이디어 주기">
</form>
{% endblock %}

IDEUS_DJANGO/ideus/templates/answer_list.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>{{ title }}|IDEUS</title>
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}
<!--모델 종류-->
<div class="Square"> 
	<h22>
        <a href="/list/question/{{ subject }}/{{ sorting }}">질문   |   </a>
        답변   |   
        <a href="/list/result/{{ subject }}/{{ sorting }}">결과물   </a>|   
    </h22>
</div>
<!--태그박스-->
<div class="Square"> 
	<h22>
        {% if subject == 'all' %}
            모두   |   
        {% else %}
            <a href="/list/answer/all/{{ sorting }}">모두   |   </a>
        {% endif %}
        
        {% for key, value in subject_dict %}
            {% if subject == key %}
                {{ value }}   |   
            {% else %}
                <a href="/list/answer/{{ key }}/{{ sorting }}">{{ value }}   </a>|   
            {% endif %}
        {% endfor %}
    </h22>
</div>
<!--정렬기준-->
<div class="Square">
    <h22>
        {% if sorting == 'my' %}
            내가 쓴 글   |   
        {% else %}
            <a href="/list/answer/{{ subject }}/my">내가 쓴 글   </a>|   
        {% endif %}
        
        {% if sorting == 'mylikes' %}
            내가 좋아한 글   |   
        {% else %}
            <a href="/list/answer/{{ subject }}/mylikes">내가 좋아한 글   </a>|   
        {% endif %}
        
        {% if sorting == 'newest' %}
            최신순   |   
        {% else %}
            <a href="/list/answer/{{ subject }}/newest">최신순   </a>|   
        {% endif %}
        
        {% if sorting == 'manylike' %}
            좋아요순   |   
        {% else %}
            <a href="/list/answer/{{ subject }}/manylike">좋아요순   </a>|   
        {% endif %}
    </h22>
</div> 
            
<!--리스트 바-->
<div id="card-wrapper">{% for answer in pageposts %}
{% for key, value in subject_dict %}
        {% if subject == 'all' or answer.question.subject == subject %}
            {% if answer.question.subject == key %}
                <div class="ListBar">
                    {% if answer.photo %}
                        <div class="main_box"><a href="{% url 'question_detail' answer.question.id %}">
                            <img src="{{ answer.photo.url }}" style="width: auto; height: 150px; border-radius: 5px;"></a></div>
                    {% else %}
                        <div class="main_box"><a href="{% url 'question_detail' answer.question.id %}">IDEUS</a></div>
                    {% endif %}
                    <div class="Square3">
                        <h24>{{ answer.title }}</h24><br>
                        <h25>{{ answer.content | slice:":150" }}</h25>
                    </div>
                    <div class="main_box">{{ value }}</div>
                    <div class="main_box" style="line-height: 75px;"><small>
                        추천 : {{ answer.like }}개</small></div>
                    </div>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endfor %}</div>

<script src="{% static 'js/InfiniteScroll.js' %}"></script>
<script type="text/javascript">
    var postWrapperId = 'card-wrapper';
    var paginatePath = '/list/question/all/newest?page=';
    var lastPage = {{ pageposts.paginator.num_pages }};
    new InfiniteScroll(paginatePath, postWrapperId, lastPage);
</script>
{% endblock %}

IDEUS_DJANGO/ideus/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
        <link rel="icon" href="{% static 'basic/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:700&display=swap" rel="stylesheet">
        {% block commands %}{% endblock %}
	</head>
	<body>
		<div id="ma">
            <script>
                var el = document.getElementById("ma");
                if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
                    el.style.width = '100%';
                } else {
                    el.style.width = '80%';
                }
            </script>
            
		    <div class="MainTitle"><a href="{% url 'index' %}" style="color:#FD7A8D;">IDEUS</a></div>
		    <div class="relative1">
                <div class="tlt" style="margin-left: 0px;"><a href="/list/question/all/newest">&nbsp;&nbsp;아이디어 보기</a></div>
                {% if user.username %}
                    <h6>&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;</h6>
		            <h7><a href="{% url 'question_new' %}" target="blank">아이디어 추천받기</a></h7>
                    <div style="float: right"><h7><a href="{% url 'mypage' %}">{{ user.username }}님 환영합니다!&nbsp;&nbsp;</a></h7></div>
                {% else %}
                    <div style="float: right"><h7><a href="{% url 'login' %}">로그인해주세요&nbsp;&nbsp;</a></h7></div>
                {% endif %}
            </div>
            {% block content %}{% endblock %}
        </div>
        <footer>
            <hr color = "#FD7A8D" size = "10px" width="100%">
            Connect to quincy0430@gmail.com OR nabinyang@gmail.com<br>
            Created by Injung.Kim and Nabin.Yang<br>
            Copyright IDEUS. All rights reserved.<br>
        </footer>
        
    </body>
</html>

IDEUS_DJANGO/ideus/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>IDEUS</title>
{% endblock %}

{% block content %}
<!--아이디어를 기다리는 글-->
<div class="Square">
    <!--제목-->
    <div class="Ast_Square">
        <h2>아이디어를 기다리는 글</h2></div>
    {% for question in waiting_question|slice:":4" %}
        <div class="Square1">
            {% if question.photo %}
                <a href="{% url 'question_detail' question.id %}"><img src="{{ question.photo.url }}" style="width: auto; max-height: 100%;"></a>
            {% else %}
                <a href="{% url 'question_detail' question.id %}"><img src="/media/ideus_basic.jpg" style="width: auto; max-height: 100%;"></a>
            {% endif %}
            <div class="Square2">&nbsp;&nbsp;&nbsp;{{ question.title }}</div>
        </div>
    {% endfor %}
    <div class="tlt"><a href="/list/question/all/noanswer">더보기</a></div>
</div>

<!--아이디어를 받은글-->
<div class="Square">
    <!--제목-->
    <div class="Ast_Square">
        <h2>아이디어를 받은 글</h2></div>
    {% for question in answer_question|slice:":4" %}
        <div class="Square1">
            {% if question.photo %}
                <a href="{% url 'question_detail' question.id %}"><img src="{{ question.photo.url }}" style="width: auto; max-height: 100%;"></a>
            {% else %}
                <a href="{% url 'question_detail' question.id %}"><img src="/media/ideus_basic.jpg" style="width: auto; max-height: 100%;"></a>
            {% endif %}
            <div class="Square2">&nbsp;&nbsp;&nbsp;{{ question.title }}</div>
        </div>
    {% endfor %}
    <div class="tlt"><a href="/list/question/all/existanswer">더보기</a></div>
</div>
{% endblock %}

IDEUS_DJANGO/ideus/templates/question_detail.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>{{ question.title }}|IDEUS</title>
<link rel="stylesheet" href="{% static 'css/question_detail.css' %}">
{% endblock %}

{% block content %}
<div class="q_box">
    Q.
    <tlt>{{ question.title }}</tlt>
    <cts><small><a href="{% url 'user_detail' question.userid %}">By.{{ question.username }}</a></small></cts><br>
    
    <cts style="font-size: 25px;">{{ question.content}}</cts><br>
    {% if question.photo %}
        <a href="{{ question.photo.url }}" target="_blank"><img src="{{ question.photo.url }}" style="width: auto; height:180px; border-radius: 5px;"></a>
    {% endif %}
    <cts><small><a href="{% url 'question_like' question.id %}">좋아요|{{ question.like }}</a></small></cts>
    <hr><cts>{{ question.subject }}/{{ question.created_at }}</cts>
    {% for result in question.result_set.all %}
        <hr>
        Production.
        <tlt>{{ result.title }}</tlt>
        <cts><small><a href="{% url 'user_detail' result.userid %}">By.{{ result.username }}</a></small></cts><br>
        <cts>{{ result.content }}</cts><br>
    
        {% if 'youtube' in result.link %}
            <iframe src="{{ result.link }}" width="320" height="180" frameborder="0" style="border-radius: 5px;" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {% elif 'vimeo' in result.link%}
            <iframe src="{{ result.link }}" width="320" height="180" frameborder="0" style="border-radius: 5px;" allow="autoplay; fullscreen" allowfullscreen></iframe>
        {% else %}
            <cts><small><a href="{{ result.link }}" target="_blank">{{ result.link }}</a></small></cts><br>
        {% endif %}
        <cts><small><a href="{% url 'result_like' result.id %}">좋아요|{{ result.like }}</a></small></cts>
    {% endfor %}
    <hr><hr>
                
    {% for answer in question.answer_set.all %}
        A.
        <tlt>{{ answer.title }}</tlt>
        <cts><small><a href="{% url 'user_detail' answer.userid %}">By.{{ answer.username }}</a></small></cts><br>
    
        <cts>{{ answer.content }}</cts><br>
        {% if answer.photo %}
                <a href="{{ answer.photo.url }}" target="_blank"><img src="{{ answer.photo.url }}" style="width: auto; height:180px; border-radius: 5px;"></a>
        {% endif %}
        <cts><small><a href="{% url 'answer_like' answer.id %}">좋아요|{{ answer.like }}</a></small></cts>
        <hr>
    {% endfor %}
    {% if user.id %}
        <cts><a href="{% url 'answer_new' question.pk %}">아이디어 주기</a> | 
        <a href="{% url 'result_new' question.pk %}">결과물 제출하기</a></cts>
    {% endif %}
</div>
{% endblock %}

IDEUS_DJANGO/ideus/templates/question_form.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>아이디어 추천받기|IDEUS</title>
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block content %}
{% if messages %}
    <hr color = "#3F3566">
    <form_title>
	{% for message in messages %}
        {{ message.message }}<br>
	{% endfor %}
    </form_title>
    <hr color = "#3F3566">
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <form_title><label for="{{form.title.id_for_label}}">제목</label></form_title>
    <input type="text" class="form-control" id="{{form.title.id_for_label}}" 
            placeholder="제목을 입력해주세요" name="{{form.title.name}}">
    
    <form_title><label for="{{form.title.id_for_label}}">주제</label></form_title>
    <select name="{{ form.subject.name }}" id="{{ form.subject.id_for_label }}">
        {% for key, value in subject %}
            <option value="{{ key }}">{{ value }}</option>
        {% endfor %}
    </select>
    <!--<input type="text" class="form-control" id="{{form.subject.id_for_label}}" 
            placeholder="주제를 입력해주세요" name="{{form.subject.name}}">-->
    
    <form_title><label for="{{form.content.id_for_label}}">내용</label></form_title>
    <textarea name="{{form.content.name}}" cols="40" rows="10" id="{{form.content.id_for_label}}" placeholder="내용을 입력해주세요"></textarea>
    
    <form_title style="color: #C6C3D1;"><label for="{{form.photo.id_for_label}}">이미지</label></form_title>
    <input type="file" name="{{ form.photo.name }}" accept="image/*" id="{{form.photo.id_for_label}}" style="background: #AC95D9;">
    
    <input type="submit" value="아이디어 추천받기">
</form>
{% endblock %}

IDEUS_DJANGO/ideus/templates/result_form.html
{% extends "base.html" %}
{% load static %}

{% block commands %}
<title>결과물 제출|IDEUS</title>
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block content %}
<h3 style="color: #3F3566"><small>※비메오와 유튜브링크를 지원합니다<br>
    유튜브또는 비메오링크를 사용할경우 맨뒤에 아이디만 남게 해주세요<br>
    ❌https://www.youtube.com/watch?v=ABCDEFGHIJ&feature=youtu.be<br>
    ⭕https://www.youtube.com/watch?v=ABCDEFGHIJ</small></h3><br>
<hr color = "#3F3566">
{% if messages %}
    <form_title>
	{% for message in messages %}
        {{ message.message }}<br>
	{% endfor %}
    </form_title>
    <hr color = "#3F3566">
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <form_title><label for="{{form.title.id_for_label}}">제목</label></form_title>
    <input type="text" class="form-control" id="{{form.title.id_for_label}}" 
            placeholder="제목을 입력해주세요" name="{{form.title.name}}">
    
    <form_title><br><label for="{{form.link.id_for_label}}">링크</label></form_title>
    <input type="url" class="form-control" id="{{form.link.id_for_label}}" 
            placeholder="링크를 입력해주세요" name="{{form.link.name}}">
    
    <form_title><br><label for="{{form.content.id_for_label}}">작품설명</label></form_title>
    <textarea name="{{form.content.name}}" cols="40" rows="10" id="{{form.content.id_for_label}}" placeholder="작품설명이 있다면 입력해주세요"></textarea>
    
    <input type="submit" value="결과물 보내기">
</form>
{% endblock %}